Update gnome runtime to 3.36
flathub/org.gnome.Rhythmbox3 pull request #30
Opened 2020-07-02 01:40 UTC by A6GibKm

* Use --socket=fallback-x11
* No need to have a default branch
* Update shared-modules

2020-07-02 09:53 UTC, hadess requested changes

2020-07-02 09:53 UTC, hadess commented on org.gnome.Rhythmbox3.json
> -    "default-branch": "stable",
The default branch is used so that the development branch, and local tests, can use another branch without affecting this one.

2020-07-02 09:53 UTC, hadess commented on org.gnome.Rhythmbox3.json
> +        "--share=ipc", "--socket=fallback-x11",
This should be in a separate commit.

2020-07-02 15:46 UTC, A6GibKm commented
I force pushed to only do the runtime change, are you ok with the `--fallback=x11` on a separate commit in this PR?

2020-09-10 07:25 UTC, A6GibKm commented
Gnome 3.34 was declared EOL in aug 14.

2020-09-21 06:56 UTC, LeonardKoenig commented
All comments are resolved I think.  For me this is the last application stopping the transition to a newer runtime.

2020-09-21 08:40 UTC, A6GibKm commented
At this point it should be updated to 3.38, note that Rhythmbox has not been updated since 3.34.

2020-09-21 15:22 UTC, hadess commented
Obsoleted by https://github.com/flathub/org.gnome.Rhythmbox3/pull/33

2020-09-21 15:22 UTC, closed without merging